import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import { TranslationProvider } from "@/hooks/useI18n";
import { headers } from "next/headers";
import { GoogleAnalytics } from "@next/third-parties/google";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const dictionaries = {
	en: () => import("public/i18n/en.json").then((module) => module.default),
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersList = await headers();
	const acceptLanguage = headersList.get("accept-language");
	// const locale = acceptLanguage?.split(",")[0] || "en";
	const locale = "en";
	console.log(locale);
	const dictionary = await dictionaries[locale as keyof typeof dictionaries]();
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className="bg-background text-foreground">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<TranslationProvider value={dictionary}>
						<Header />
						{children}
						<Footer />
					</TranslationProvider>
				</ThemeProvider>
				<GoogleAnalytics gaId="G-89618T8EX2"/>
			</body>
		</html>
	);
}
